services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_hunter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 15s
      timeout: 15s
      retries: 15

  
  fastapi:
    build: ./MyProject/fastapi
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
